version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    assignees:
      - "ervwalter"
    commit-message:
      prefix: "deps"
    groups:
      npm-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      npm-major:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "nuget"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    assignees:
      - "ervwalter"
    commit-message:
      prefix: "deps"
    groups:
      nuget-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      nuget-major:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    assignees:
      - "ervwalter"
    commit-message:
      prefix: "deps"
    groups:
      docker-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      docker-major:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    assignees:
      - "ervwalter"
    commit-message:
      prefix: "deps"
    groups:
      github-actions-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      github-actions-major:
        patterns:
          - "*"
        update-types:
          - "major"
