# ./.tmuxinator.yml

name: trendweight
root: ./

# Create logs directory and set up exit hooks
on_project_start: |
  mkdir -p logs
  tmux set-hook -g pane-exited 'if -F "#{==:#{session_name},trendweight}" "kill-session -t trendweight"'

windows:
  - dev:
      layout: even-horizontal
      panes:
        - frontend:
            - cd apps/web
            - tmux pipe-pane -t 0 "perl -pe '$|=1; s/\\e\\[[0-9;?]*[a-zA-Z]//g; s/\\\\\\].*?\\\\//g; s/\\e\\].*?\\007//g; s/\\r//g; s/\\e=//g' > logs/frontend.log 2>&1"
            - clear
            - exec bash -c "trap 'tmux kill-session -t trendweight' EXIT; npm run dev"
        - backend:
            - cd apps/api/TrendWeight
            - tmux pipe-pane -t 1 "perl -pe '$|=1; s/\\e\\[[0-9;?]*[a-zA-Z]//g; s/\\\\\\].*?\\\\//g; s/\\e\\].*?\\007//g; s/\\r//g; s/\\e=//g' > logs/backend.log 2>&1"
            - clear
            - exec bash -c "trap 'tmux kill-session -t trendweight' EXIT; dotnet watch"